apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: edge-sqlite-pvc
  namespace: smart-greenhouse
  labels:
    app: edge-processor
    tier: storage
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
